import express from "express";
import { compare } from "../controllers/compare.js";
import { connection } from "../controllers/connection.js";
import { sendfile } from "../controllers/compare.js";
const route = express.Router();
export const datafromDb = [];
route.get("/get", (req, res) => res.send("get value"));
route.post("/createConnection", connection);
route.post("/compare", compare);
route.get("/getfile", sendfile);
export default route;
